version: 2.1

jobs: 
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: test-env-vars
          command: echo $(TestingEnvVars}

workflows:
  test-env-vars:
    jobs:
      - build
